server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dbAdmin
    password: 1234
    hikari:
      connection-test-query: SELECT 1 
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
         
  